spring:
  application:
    name: cloudgateway
  profiles:
    active: "dev"

server:
  port: ${PORT:9001}
  
zuul:
  routes:
    testservce:
      path: /testservice/**
      serviceId: testservice
    repository:
      path: /repository/**
      serviceId: repository
    planing:
      path: /planing/**
      serviceId: planing
    inputadapter:
      path: /inputadapter/**
      serviceId: inputadapter
    preprocessing:
      path: /preprocessing/**
      serviceId: preprocessing
    outputadapter:
      path: /outputadapter/**
      serviceId: outputadapter

---
spring:
  profiles: dev
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    enabled: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    
zuul:
  routes:
    eureka:
      path: /eureka/**
      url: http://localhost:9000
      
---
spring:
  profiles: docker
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://serviceregistration:9000/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    
zuul:
  routes:
    eureka:
      path: /eureka/**
      url: http://serviceregistration:9000
      
---
spring:
  profiles: aws
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://${SERVICE_REGISTRATION_PRIVATE_IP}:9000/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    homePageUrl: http://${PRIVATE_IP}:9011/
    
zuul:
  routes:
    eureka:
      path: /eureka/**
      url: http://${SERVICE_REGISTRATION_PRIVATE_IP}:9000