spring:
  application:
    name: zuulproxy
  profiles:
    active: "dev"

server:
  port: ${PORT:9001}

---
spring:
  profiles: dev
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    
zuul:
  routes:
    eureka:
      path: /eureka/**
      url: http://localhost:9000
    testservice:
      path: /testservice/**
      url: http://localhost:9010
    repositoryservice:
      path: /repositoryservice/**
      url: http://localhost:9011
    planingservice:
      path: /planingservice/**
      url: http://localhost:9012
      
---
spring:
  profiles: docker
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://serviceregistration:9000/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    
zuul:
  routes:
    eureka:
      path: /eureka/**
      url: http://serviceregistration:9000
    testservice:
      path: /testservice/**
      url: http://testservice:9010
    repositoryservice:
      path: /repositoryservice/**
      url: http://repository:9011
    planingservice:
      path: /planingservice/**
      url: http://planing:9012